services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 #얘는 컨테이너 환경일때
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  auth-db:
    image: mongo:6
    container_name: auth-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - auth_db_data:/data/db

  event-db:
    image: mongo:6
    container_name: event-db
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - event_db_data:/data/db
volumes:
  event_db_data:
  auth_db_data:
